---
title: "BIOSTAT 620 Introduction to Health Data Science"
---

## Course Information

* Instructor: [Dylan Cable](https://sph.umich.edu/faculty-profiles/cable-dylan.html) [[dmcable@umich.edu](mailto:dmcable@umich.edu)]
* Graduate student instructor:  Yize Hao [[yizehao@umich.edu](mailto:yizehao@umich.edu)]
* Location: SPH I 1655
* Date and time: Tue & Thu 8:30 - 10:00am
* Textbooks: <https://github.com/rafalab/dsbook-part-1>, <https://github.com/rafalab/dsbook-part-2>
* Canvas: <https://umich.instructure.com/courses/727331>
* GitHub repo: <https://github.com/dmcable/BIOSTAT620>
* Remember to read the [syllabus](syllabus.qmd), [listen to SD](https://www.youtube.com/embed/aL_fP5axQV4).

## Lectures 

Lecture slides, class notes, and problem sets are linked below. New material is added approximately on a weekly basis.

| Dates   | Topic  |    Slides | Reading |
|:-------------------|:---------|:----------|:----------|
| Jan 09 | Productivity Tools| [Intro](slides/00-intro.qmd), [Unix](slides/productivity/01-unix.qmd), [RStudio](slides/productivity/02-rstudio.qmd)| Installing R and RStudio on [Windows](https://teacherscollege.screenstepslive.com/a/1108074-install-r-and-rstudio-for-windows) or [Mac](https://teacherscollege.screenstepslive.com/a/1135059-install-r-and-rstudio-for-mac), [Getting Started](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/getting-started.html), [Unix](http://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/unix.html)|
| Jan 14| Productivity Tools|  [Quarto](slides/productivity/03-quarto.qmd), [Git and GitHub](slides/productivity/04-git.qmd) | [RStudio Projects, Quarto](https://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/reproducible-projects.html), [Git](http://rafalab.dfci.harvard.edu/dsbook-part-1/productivity/git.html) |
Jan 16 | Data processing in R | [R basics](slides/R/05-r-basics.qmd), [Vectorization](slides/R/06-vectorization.qmd) |  [R Basics](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/R-basics.html), [Vectorization](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/programming-basics.html#sec-vectorization) |
|Jan 16 | Data Processing in R | [Tidyverse](slides/R/07-tidyverse.qmd), [ggplot2](slides/R/08-ggplot2.qmd) | [dplyr](http://rafalab.dfci.harvard.edu/dsbook-part-1/R/tidyverse.html), [ggplot2](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/ggplot2.html) |
| Jan 21 | Data Processing in R | [Tyding data](slides/R/09-tidyr.qmd) | [Reshaping Data](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/reshaping-data.html)
| Jan 21, Jan 23 | Wrangling  | [Intro](slides/wrangling/10-intro-to-wrangling.qmd), [Data Importing](slides/wrangling/11-importing-files.qmd), [Dates and Times](slides/wrangling/12-dates-and-times.qmd), [Locales](slides/wrangling/13-locales.qmd), [Data APIs](slides/wrangling/14-data-apis.qmd), [Web scraping](slides/wrangling/15-web-scraping.qmd), [Joining tables](slides/wrangling/16-joining-tables.qmd) | [Importing data](https://rafalab.dfci.harvard.edu/dsbook-part-1/R/importing-data.html), [dates and times](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/dates-and-times.html), [Locales](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/locales.html), [Joining Tables](http://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/joining-tables.html), [Extracting data from the web](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/web-scraping.html)|
| Jan 28, Jan 30 | Data visualization  | [Dataviz Principles](slides/dataviz/17-dataviz-principles.qmd), [Distributions](slides/dataviz/18-distributions.qmd), [Dataviz in practice](slides/dataviz/19-dataviz-in-practice.qmd)| [Distributions](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/distributions.html), [Dataviz Principles](http://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/dataviz-principles.html) 
| Feb 04 | Probability   | [Intro](slides/prob/20-intro-to-prob.qmd), [Foundations for Inference](slides/prob/21-inference-foundations.qmd)| [Monte Carlo](http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/continuous-probability.html#monte-carlo), [Random Variables & CLT](http://rafalab.dfci.harvard.edu/dsbook-part-2/prob/random-variables-sampling-models-clt.html)|
| Feb 06 | Inference | [Intro](slides/inference/22-intro-inference.qmd), [Parameter and estimates](slides/inference/23-parameters-estimates.qmd), [Confidence Intervals](slides/inference/24-confidence-intervals.qmd) | [Parameters & Estimates](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/parameters-estimates.html), [Confidence Intervals](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/confidence-intervals.html) |
| Feb 11, Feb 13 | Statistical Models | [Models](slides/inference/25-models.qmd), [Bayes](slides/inference/26-bayes.qmd), [Hierarchical Models](slides/inference/27-hierarchical-models.qmd) | [Data-driven Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/models.html),  [Bayesian Statistics](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/bayes.html), [Hierarchical Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/inference/hierarchical-models.html) |
| Feb 18 | Midterm 1 | | Covers material from Jan 09-Feb 13|
| Feb 20, Feb 25 |  Linear models  | [Intro](slides/linear-models/28-intro-to-linear-models.qmd), [Regression](slides/linear-models/29-regression.qmd) |  [Regression](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/regression.html), [Multivariate Regression](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/multivariate-regression.html) |
| Feb 27, Mar 11 |  Linear models  | [Multivariate regression](slides/linear-models/30-multivariate-regression.qmd), [Treatment effect models](slides/linear-models/31-treatment-effect-models.qmd) |  [Measurement Error Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/measurement-error-models.html), [Treatment Effect Models](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/treatment-effect-models.html), [Association Tests](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-tests.html), [Association Not Causation](http://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-not-causation.html) |
Mar 13 | High dimensional data| [Intro to Linear Algebra](slides/highdim/32-linear-algebra-intro.qmd), [Matrices in R](slides/highdim/33-matrices-in-R.qmd) | [Matrices in R](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/matrices-in-R.html), [Applied Linear Algebra](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/linear-algebra.html), |
| Mar 18 | High dimensional data | [Distance](slides/highdim/34-distance.qmd), [Dimension reduction](slides/highdim/35-dimension-reduction.qmd) |[Dimension Reduction](https://rafalab.dfci.harvard.edu/dsbook-part-2/highdim/dimension-reduction.html) |


<!--


| Nov 25 | Midterm 2 | | Midterm 2: cover material from Sep 04-Nov 22|

| Dec 04 | Machine Learning | [Intro](slides/ml/36-intro-ml.qmd), [Metrics](slides/ml/37-evaluation-metrics.qmd), [Conditionals](slides/ml/38-conditionals.qmd), [Smoothing](slides/ml/39-smoothing.qmd)|[Notation and terminology](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/notation-and-terminology.html), [Evaluation Metrics](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/evaluation-metrics.html), [conditional probabilities](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/conditionals.html), [smoothing](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/smoothing.html) |
|  Dec 09, Dec 11 | Machine Learning | [kNN](slides/ml/40-knn.qmd), [Resampling methods](slides/ml/41-resampling-methods.qmd), [caret package](slides/ml/42-caret.qmd), [Algorithms](slides/ml/43-algorithms.qmd), [ML in practice](slides/ml/44-ml-in-practice.qmd)|[Resampling methods](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/resampling-methods.html), [ML algorithms](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/algorithms.html), [ML in practice](https://rafalab.dfci.harvard.edu/dsbook-part-2/ml/ml-in-practice.html) |
| Dec 16, Dec 18 | Other topics  | [Association is not causation](slides/other-topics/45-association-not-causation.qmd), [Shiny](slides/other-topics/46-shiny.qmd), [Shiny example code](https://github.com/datasciencelabs/2024/tree/main/shiny)| [Association is not causation](https://rafalab.dfci.harvard.edu/dsbook-part-2/linear-models/association-not-causation.html) |
-->

## Problem sets

| Problem set| Topic | Due Date (11:59pm) |  Difficulty |
|:-------|:--------------|:---------|:----------|
[01](psets/pset-01-unix-quarto.html)   |  Unix, Quarto|Jan 19   | easy | 
[02](psets/pset-02-R-data-analysis.html) |  Data analysis with R | Jan 26  |medium | 
[03](psets/pset-03-wrangling.qmd)          | Wrangling | Feb 2   |medium 
[04](psets/pset-04-dataviz.qmd)          | Dataviz | Feb 9   | medium |
| [05](psets/pset-05-prob.qmd)          | Probability | Feb 23   | medium | 
| [06](psets/pset-06-election.qmd)          | Predict the election | Mar 02   |  hard | 
| [07](psets/pset-07-linear-models.qmd)          | Excess mortality after Hurricane María | Mar 16   |  medium | 


<!--
| [09](psets/pset-09-matrices.qmd)          | Matrices | Nov 22   | easy | 
| [10](psets/pset-10-ml.qmd)          | Digit reading | Dec 16   | hard | 
|Final Project| Your choice | Dec 20   | hard  |-->

## Office hour times

| Meeting | Time  | Location                 |
|---------|----------|------------------------|
| Dylan Cable  | Wed      2:00-3:00PM   |  SPH I 4635   |
| Yize Hao | Fri 10:00-11:00AM     | SPH II M4034      |
<!--| Nikhil Vytla   | Wed      2:00-3:00PM     | Kresge 201         |
| Yuan Wang | Fri    1:00-2:00PM     | [Zoom](https://harvard.zoom.us/j/98901120095?pwd=CrhPTA0Nco2rY6ggzYIfq6kQmP4VZn.1) |-->

## Acknowledgments

We thank [Maria Tackett](https://github.com/matackett) and [Mine Çetinkaya-Rundel](https://github.com/mine-cetinkaya-rundel) for sharing their [web page template](https://github.com/rstudio-conf-2022/teach-ds-course-website/tree/main), which we used in creating this website. We thank [Rafael Irizarry](https://github.com/rafalab) for sharing materials.

